# -*- coding: utf-8 -*-
"""FocusU_etapa2 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R9RF-kra2YYPC6sPCKMRZiqHyvvzovDl
"""

from abc import ABC, abstractmethod

# Classe que serve de modelo de herança. Possui atributos
# estáticos de contagem e métodos abstratos herdados.

class UsuarioBase(ABC):
    total_usuarios = 0

    def __init__(self, nome, email):
        self._nome = nome
        self._email = email
        UsuarioBase.total_usuarios += 1

    def __del__(self):
        if UsuarioBase.total_usuarios > 0:
            UsuarioBase.total_usuarios -= 1


    # CONCEITO: ENCAPSULAMENTO
    @property
    def nome(self):
        return self._nome

    @nome.setter
    def nome(self, valor):
        if not valor.strip():
            raise ValueError("Nome não pode ser vazio.")
        self._nome = valor

    @property
    def email(self):
        return self._email

    @email.setter
    def email(self, valor):
        if "@" not in valor:
            raise ValueError("Email inválido.")
        self._email = valor


    # CONCEITO: MÉTODO ABSTRATO
    # Força as classes filhas a implementarem sua própria versão.

    @abstractmethod
    def exibir_perfil(self):
        pass


# CONCEITO: HERANÇA
# Classe Aluno estende a classe abstrata UsuarioBase.

class Aluno(UsuarioBase):
    def __init__(self, nome, email, matricula):
        super().__init__(nome, email)
        self.matricula = matricula


        # CONCEITO: ASSOCIAÇÃO
        # Armazena internamente referências de objetos de outras classes.
        self.disciplinas = []
        self.rotinas = []

    def adicionar_disciplina(self, disciplina):
        self.disciplinas.append(disciplina)

    def adicionar_rotina(self, rotina):
        self.rotinas.append(rotina)

    def exibir_perfil(self):
        return f"Aluno: {self.nome} | Matrícula: {self.matricula}"

    def __str__(self):
        return self.exibir_perfil()


# CONCEITO: INTERFACE
# Define um contrato de comportamento obrigatório para o Feed.

class Publicavel(ABC):
    @abstractmethod
    def publicar(self):
        pass


# CONCEITO: IMPLEMENTAÇÃO DE INTERFACE
# Classe Postagem assina e implementa o contrato de Publicavel.

class Postagem(Publicavel):
    total_postagens = 0

    def __init__(self, titulo, conteudo, autor):
        self.titulo = titulo
        self.conteudo = conteudo
        self.autor = autor
        self.curtidas = 0
        self.comentarios = []
        Postagem.total_postagens += 1

    def __del__(self):
        if Postagem.total_postagens > 0:
            Postagem.total_postagens -= 1

    @property
    def titulo(self):
        return self._titulo

    @titulo.setter
    def titulo(self, valor):
        if not valor.strip():
            raise ValueError("Título não pode ser vazio.")
        self._titulo = valor

    @property
    def conteudo(self):
        return self._conteudo

    @conteudo.setter
    def conteudo(self, valor):
        if not valor.strip():
            raise ValueError("Conteúdo não pode ser vazio.")
        self._conteudo = valor

    def curtir(self):
        self.curtidas += 1

    def comentar(self, comentario):
        self.comentarios.append(comentario)

    def publicar(self):
        nome_autor = self.autor.nome if self.autor else "Usuário Anônimo"
        return (
            f"\n[POST GERAL]\n"
            f"Título: {self.titulo}\n"
            f"Autor: {nome_autor}\n"
            f"Conteúdo: {self.conteudo}\n"
            f"Curtidas: {self.curtidas} | Comentários: {len(self.comentarios)}"
        )


# CONCEITO: HERANÇA E POLIMORFISMO
# Especializações de Postagem que alteram o método publicar().

class PostagemDuvida(Postagem):
    def __init__(self, titulo, conteudo, autor, disciplina):
        super().__init__(titulo, conteudo, autor)
        self.disciplina = disciplina
        self.resolvida = False

    # Sobrescrita Polimórfica: adiciona status e metadados específicos
    def publicar(self):
        nome_autor = self.autor.nome if self.autor else "Usuário Anônimo"
        status = "[RESOLVIDA]" if self.resolvida else "[ABERTA]"
        return (
            f"\n[DÚVIDA - {self.disciplina.upper()}] {status}\n"
            f"Título: {self.titulo}\n"
            f"Autor: {nome_autor}\n"
            f"Conteúdo: {self.conteudo}\n"
            f"Curtidas: {self.curtidas} | Comentários: {len(self.comentarios)}"
        )


class PostagemMaterial(Postagem):
    def __init__(self, titulo, conteudo, autor, link_download):
        super().__init__(titulo, conteudo, autor)
        self.link_download = link_download

    # Sobrescrita Polimórfica: inclui link de download na visualização
    def publicar(self):
        nome_autor = self.autor.nome if self.autor else "Usuário Anônimo"
        return (
            f"\n[MATERIAL COMPARTILHADO]\n"
            f"Título: {self.titulo}\n"
            f"Autor: {nome_autor}\n"
            f"Conteúdo: {self.conteudo}\n"
            f"Link de Download: {self.link_download}\n"
            f"Curtidas: {self.curtidas} | Comentários: {len(self.comentarios)}"
        )


# CONCEITO: POLIMORFISMO
# Implementa de forma independente a interface Publicavel.

class Evento(Publicavel):
    total_eventos = 0

    def __init__(self, titulo, data, horario):
        self.titulo = titulo
        self.data = data
        self.horario = horario
        Evento.total_eventos += 1

    def __del__(self):
        if Evento.total_eventos > 0:
            Evento.total_eventos -= 1

    @property
    def titulo(self):
        return self._titulo

    @titulo.setter
    def titulo(self, valor):
        if not valor.strip():
            raise ValueError("Título inválido.")
        self._titulo = valor

    # Implementação do método do contrato
    def publicar(self):
        return (
            f"\n[EVENTO ACADÊMICO]\n"
            f"Título: {self.titulo}\n"
            f"Data: {self.data}\n"
            f"Horário: {self.horario}"
        )


class Disciplina:
    total_disciplinas = 0
    def __init__(self, nome, professor):
        self._nome = nome
        self.professor = professor
        Disciplina.total_disciplinas += 1
    def __del__(self):
        if Disciplina.total_disciplinas > 0: Disciplina.total_disciplinas -= 1

    @property
    def nome(self):
        return self._nome

    @nome.setter
    def nome(self, valor):
        if not valor.strip(): raise ValueError("Nome inválido.")
        self._nome = valor

    def __str__(self): return f"Disciplina: {self.nome} | Prof: {self.professor}"


class Rotina:
    total_rotinas = 0
    def __init__(self, atividade, tempo):
        self._atividade = atividade
        self.tempo = tempo
        Rotina.total_rotinas += 1
    def __del__(self):
        if Rotina.total_rotinas > 0: Rotina.total_rotinas -= 1
    @property
    def atividade(self): return self._atividade
    @atividade.setter
    def atividade(self, valor):
        if not valor.strip(): raise ValueError("Atividade inválida.")
        self._atividade = valor
    @property
    def tempo(self): return self._tempo
    @tempo.setter
    def tempo(self, valor):
        if valor <= 0: raise ValueError("Tempo deve ser maior que zero.")
        self._tempo = valor
    def __str__(self): return f"{self.atividade} | {self.tempo} min"



# CLASSE GEERENCIADORA
# Centraliza métodos de controle

class SistemaFocusU:
    def __init__(self):
        self.alunos = []
        self.disciplinas_globais = []
        self.postagens = []
        self.eventos = []

    def adicionar_aluno(self, aluno): self.alunos.append(aluno)

    # Exclusão segura
    def remover_aluno(self, aluno):
        # Quebra de associação direta mantendo integridade da postagem (Anonimização)
        for post in self.postagens:
            if post.autor == aluno:
                post.autor = None

        for rotina in aluno.rotinas:
            rotina.__del__()
        for disc in aluno.disciplinas:
            if disc in self.disciplinas_globais:
                self.disciplinas_globais.remove(disc)
            disc.__del__()

        if aluno in self.alunos:
            self.alunos.remove(aluno)
            aluno.__del__()

    def adicionar_disciplina_global(self, d): self.disciplinas_globais.append(d)
    def adicionar_postagem(self, p): self.postagens.append(p)
    def adicionar_evento(self, e): self.eventos.append(e)

    def listar_alunos(self):
        print("\n===== ALUNOS =====")
        if not self.alunos: print("Nenhum cadastrado.")
        for a in self.alunos:
            print(a)
            if a.disciplinas:
                print("  Disciplinas Matriculadas:", [d.nome for d in a.disciplinas])
            if a.rotinas:
                print("  Plano de Rotinas:")
                for r in a.rotinas:
                    print(f"   - {r}")


    # CONCEITO: EXECUÇÃO DO POLIMORFISMO
    # O motor itera sobre uma coleção genérica de objetos 'Publicavel'
    # executando a chamada polimórfica única sem checagem de tipos

    def exibir_feed(self):
        print("\n===== FEED FOCUS U =====")
        feed = self.postagens + self.eventos
        if not feed:
            print("Feed vazio.")
            return
        for item in feed:
            print(item.publicar())  # Chamada dinâmica polimórfica
            print("-" * 40)


    def estatisticas(self):
        print("\n===== ESTATÍSTICAS =====")
        print(f"Alunos Ativos: {UsuarioBase.total_usuarios}")
        print(f"Postagens Ativas: {Postagem.total_postagens}")
        print(f"Disciplinas no App: {Disciplina.total_disciplinas}")
        print(f"Rotinas Existentes: {Rotina.total_rotinas}")



sistema = SistemaFocusU()

while True:
    print("\n════════════════════════════")
    print("         FOCUS U 2.0")
    print("════════════════════════════")
    print("1 - Cadastro")
    print("2 - Criar Disciplina Geral")
    print("3 - Vincular Disciplina ao Aluno")
    print("4 - Criar Rotina para Aluno")
    print("5 - Criar Postagem (Geral, Dúvida ou Material)")
    print("6 - Criar Evento")
    print("7 - Listar Alunos e suas Rotinas")
    print("8 - Exibir Feed")
    print("9 - Curtir Postagem")
    print("10 - Comentar Postagem")
    print("11 - Estatísticas")
    print("12 - Apagar Conta")
    print("0 - Sair")

    opcao = input("\nEscolha uma opção: ")

    try:
        if opcao == "1":
            mat = input("Matrícula: ")
            nome = input("Nome de Usuário: ")
            email = input("Email: ")

            matricula_repetida = False
            nome_repetido = False
            email_repetido = False

            for a in sistema.alunos:
                if a.matricula.strip() == mat.strip():
                    matricula_repetida = True
                    break
                if a.nome.strip().lower() == nome.strip().lower():
                    nome_repetido = True
                    break
                if a.email.strip().lower() == email.strip().lower():
                    email_repetido = True
                    break

            if matricula_repetida:
                print(f"\n[AÇÃO CANCELADA]: A matrícula '{mat}' já está cadastrada!")
                continue

            if nome_repetido:
                print(f"\n[AÇÃO CANCELADA]: O nome de usuário '{nome}' já está em uso!")
                continue

            if email_repetido:
                print(f"\n[AÇÃO CANCELADA]: O e-mail '{email}' já está cadastrado em outra conta!")
                continue

            sistema.adicionar_aluno(Aluno(nome, email, mat))
            print("\nAluno cadastrado com sucesso!")

        elif opcao == "2":
            nome, prof = input("Disciplina: "), input("Professor: ")
            sistema.adicionar_disciplina_global(Disciplina(nome, prof))
            print("\nDisciplina criada no sistema!")

        elif opcao == "3":
            if not sistema.alunos or not sistema.disciplinas_globais:
                print("Cadastre alunos e disciplinas primeiro."); continue

            for i, a in enumerate(sistema.alunos): print(f"{i} - {a.nome}")
            idx_a = int(input("Escolha o aluno: "))
            if idx_a < 0: raise IndexError("Índices negativos não são permitidos.")

            for i, d in enumerate(sistema.disciplinas_globais): print(f"{i} - {d.nome}")
            idx_d = int(input("Escolha a disciplina: "))
            if idx_d < 0: raise IndexError("Índices negativos não são permitidos.")

            sistema.alunos[idx_a].adicionar_disciplina(sistema.disciplinas_globais[idx_d])
            print("\nMatrícula na disciplina efetuada!")

        elif opcao == "4":
            if not sistema.alunos: print("Cadastre um aluno primeiro."); continue
            for i, a in enumerate(sistema.alunos): print(f"{i} - {a.nome}")
            idx = int(input("Escolha o aluno dono da rotina: "))
            if idx < 0: raise IndexError("Índices negativos não são permitidos.")

            atv, temp = input("Atividade: "), int(input("Tempo (min): "))
            sistema.alunos[idx].adicionar_rotina(Rotina(atv, temp))
            print("\nRotina salva no perfil do aluno!")

        elif opcao == "5":
            if not sistema.alunos: print("Cadastre um aluno primeiro."); continue
            for i, a in enumerate(sistema.alunos): print(f"{i} - {a.nome}")
            idx = int(input("Autor: "))
            if idx < 0: raise IndexError("Índices negativos não são permitidos.")

            print("\nTipo: 1-Geral | 2-Dúvida | 3-Material")
            tipo = input("Escolha: ")
            t, c = input("Título: "), input("Conteúdo: ")

            if tipo == "2":
                disc = input("Disciplina da dúvida: ")
                p = PostagemDuvida(t, c, sistema.alunos[idx], disc)
            elif tipo == "3":
                link = input("Link do material: ")
                p = PostagemMaterial(t, c, sistema.alunos[idx], link)
            else:
                p = Postagem(t, c, sistema.alunos[idx])

            sistema.adicionar_postagem(p)
            print("\nPostagem enviada ao feed!")

        elif opcao == "6":
            t, d, h = input("Título: "), input("Data: "), input("Horário: ")
            sistema.adicionar_evento(Evento(t, d, h))
            print("\nEvento publicado!")

        elif opcao == "7": sistema.listar_alunos()
        elif opcao == "8": sistema.exibir_feed()

        elif opcao == "9":
            if not sistema.postagens: print("Nenhum post disponível."); continue
            for i, p in enumerate(sistema.postagens): print(f"{i} - {p.titulo}")
            idx = int(input("Escolha o post: "))
            if idx < 0: raise IndexError("Índices negativos não são permitidos.")
            sistema.postagens[idx].curtir()
            print("\nVocê curtiu essa publicação!")

        elif opcao == "10":
            if not sistema.postagens: print("Nenhum post disponível."); continue
            for i, p in enumerate(sistema.postagens): print(f"{i} - {p.titulo}")
            idx = int(input("Escolha o post: "))
            if idx < 0: raise IndexError("Índices negativos não são permitidos.")
            coment = input("Comentário: ")
            sistema.postagens[idx].comentar(coment)
            print("\nComentário publicado!")

        elif opcao == "11": sistema.estatisticas()

        elif opcao == "12":
            if not sistema.alunos: print("Nenhum aluno no sistema."); continue
            for i, a in enumerate(sistema.alunos): print(f"{i} - {a.nome}")
            idx = int(input("Remover ID: "))
            if idx < 0: raise IndexError("Índices negativos não são permitidos.")
            aluno_alvo = sistema.alunos[idx]
            sistema.remover_aluno(aluno_alvo)
            print(f"\nConta de {aluno_alvo.nome} e suas rotinas foram apagadas!")

        elif opcao == "0": break

    except (ValueError, IndexError) as erro_especifico:
        print(f"\n[AÇÃO INTERRUPTIDA]: Entrada inválida ou operação incorreta. ({erro_especifico})")
    except Exception as erro:
        print(f"\nErro operacional: {erro}")