# -*- coding: utf-8 -*-
"""codigo_base.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B9zlRq9oTzl_zdBMRN_ZgaFVPQUUWLyq
"""

from abc import ABfC, abstractmethod


# =====================================================
# SUPERCLASSE ABSTRATA
# =====================================================

class UsuarioBase(ABC):

    total_usuarios = 0

    def __init__(self, nome, email):

        self.nome = nome
        self.email = email

        UsuarioBase.total_usuarios += 1

    # =====================================
    # PROPERTY - NOME
    # =====================================

    @property
    def nome(self):
        return self._nome

    @nome.setter
    def nome(self, valor):

        if not valor.strip():
            raise ValueError(
                "Nome não pode ser vazio."
            )

        self._nome = valor

    # =====================================
    # PROPERTY - EMAIL
    # =====================================

    @property
    def email(self):
        return self._email

    @email.setter
    def email(self, valor):

        if "@" not in valor:
            raise ValueError(
                "Email inválido."
            )

        self._email = valor

    # =====================================
    # MÉTODO ABSTRATO
    # =====================================

    @abstractmethod
    def exibir_perfil(self):
        pass


# =====================================================
# CLASSE ALUNO
# =====================================================

class Aluno(UsuarioBase):

    def __init__(
        self,
        nome,
        email,
        matricula
    ):

        super().__init__(
            nome,
            email
        )

        self.matricula = matricula

        # Associação
        # Cada aluno possui disciplinas

        self.disciplinas = []

    def adicionar_disciplina(
        self,
        disciplina
    ):

        self.disciplinas.append(
            disciplina
        )

    def exibir_perfil(self):

        return (
            f"Aluno: {self.nome} | "
            f"Matrícula: {self.matricula}"
        )

    def __str__(self):

        return self.exibir_perfil()

# =====================================================
# INTERFACE
# =====================================================

class Publicavel(ABC):

    @abstractmethod
    def publicar(self):
        pass


# =====================================================
# CLASSE POSTAGEM
# =====================================================

class Postagem(Publicavel):

    total_postagens = 0

    def __init__(
        self,
        titulo,
        conteudo,
        autor
    ):

        self.titulo = titulo
        self.conteudo = conteudo
        self.autor = autor

        self.curtidas = 0
        self.comentarios = []

        Postagem.total_postagens += 1

    # =====================================
    # PROPERTY - TITULO
    # =====================================

    @property
    def titulo(self):
        return self._titulo

    @titulo.setter
    def titulo(self, valor):

        if not valor.strip():
            raise ValueError(
                "Título não pode ser vazio."
            )

        self._titulo = valor

    # =====================================
    # PROPERTY - CONTEUDO
    # =====================================

    @property
    def conteudo(self):
        return self._conteudo

    @conteudo.setter
    def conteudo(self, valor):

        if not valor.strip():
            raise ValueError(
                "Conteúdo não pode ser vazio."
            )

        self._conteudo = valor

    # =====================================
    # MÉTODOS DE INSTÂNCIA
    # =====================================

    def curtir(self):

        self.curtidas += 1

    def comentar(
        self,
        comentario
    ):

        self.comentarios.append(
            comentario
        )

    # =====================================
    # POLIMORFISMO
    # =====================================

    def publicar(self):

        return (
            f"\nPOSTAGEM\n"
            f"Título: {self.titulo}\n"
            f"Autor: {self.autor.nome}\n"
            f"Conteúdo: {self.conteudo}\n"
            f"Curtidas: {self.curtidas}\n"
            f"Comentários: {len(self.comentarios)}"
        )

    def __str__(self):

        return self.publicar()


# =====================================================
# CLASSE EVENTO
# =====================================================

class Evento(Publicavel):

    total_eventos = 0

    def __init__(
        self,
        titulo,
        data,
        horario
    ):

        self.titulo = titulo
        self.data = data
        self.horario = horario

        Evento.total_eventos += 1

    @property
    def titulo(self):
        return self._titulo

    @titulo.setter
    def titulo(self, valor):

        if not valor.strip():
            raise ValueError(
                "Título inválido."
            )

        self._titulo = valor

    # =====================================
    # POLIMORFISMO
    # =====================================

    def publicar(self):

        return (
            f"\nEVENTO\n"
            f"Título: {self.titulo}\n"
            f"Data: {self.data}\n"
            f"Horário: {self.horario}"
        )

    def __str__(self):

        return self.publicar()
# =====================================================
# CLASSE DISCIPLINA
# =====================================================

class Disciplina:

    total_disciplinas = 0

    def __init__(
        self,
        nome,
        professor
    ):

        self.nome = nome
        self.professor = professor

        Disciplina.total_disciplinas += 1

    @property
    def nome(self):
        return self._nome

    @nome.setter
    def nome(self, valor):

        if not valor.strip():
            raise ValueError(
                "Nome da disciplina inválido."
            )

        self._nome = valor

    def __str__(self):

        return (
            f"Disciplina: {self.nome} | "
            f"Professor: {self.professor}"
        )


# =====================================================
# CLASSE ROTINA
# =====================================================

class Rotina:

    total_rotinas = 0

    def __init__(
        self,
        atividade,
        tempo
    ):

        self.atividade = atividade
        self.tempo = tempo

        Rotina.total_rotinas += 1

    @property
    def tempo(self):
        return self._tempo

    @tempo.setter
    def tempo(self, valor):

        if valor <= 0:
            raise ValueError(
                "Tempo deve ser maior que zero."
            )

        self._tempo = valor

    def __str__(self):

        return (
            f"Atividade: {self.atividade} | "
            f"Tempo: {self.tempo} min"
        )


# =====================================================
# CLASSE SISTEMAFOCUSU
# =====================================================

class SistemaFocusU:

    def __init__(self):

        self.alunos = []
        self.disciplinas = []
        self.rotinas = []
        self.postagens = []
        self.eventos = []

    # =====================================
    # CADASTROS
    # =====================================

    def adicionar_aluno(
        self,
        aluno
    ):

        self.alunos.append(
            aluno
        )

    def adicionar_disciplina(
        self,
        disciplina
    ):

        self.disciplinas.append(
            disciplina
        )

    def adicionar_rotina(
        self,
        rotina
    ):

        self.rotinas.append(
            rotina
        )

    def adicionar_postagem(
        self,
        postagem
    ):

        self.postagens.append(
            postagem
        )

    def adicionar_evento(
        self,
        evento
    ):

        self.eventos.append(
            evento
        )

    # =====================================
    # LISTAGENS
    # =====================================

    def listar_alunos(self):

        print("\n===== ALUNOS =====")

        if not self.alunos:
            print("Nenhum aluno cadastrado.")
            return

        for aluno in self.alunos:

            print(aluno)

            if aluno.disciplinas:

                print("Disciplinas:")

                for disciplina in aluno.disciplinas:

                    print(
                        f" - {disciplina.nome}"
                    )

    def listar_disciplinas(self):

        print("\n===== DISCIPLINAS =====")

        if not self.disciplinas:
            print("Nenhuma disciplina.")
            return

        for disciplina in self.disciplinas:
            print(disciplina)

    def listar_rotinas(self):

        print("\n===== ROTINAS =====")

        if not self.rotinas:
            print("Nenhuma rotina.")
            return

        for rotina in self.rotinas:
            print(rotina)

    # =====================================
    # FEED POLIMÓRFICO
    # =====================================

    def exibir_feed(self):

        print("\n===== FEED FOCUS U =====")

        feed = []

        for postagem in self.postagens:
            feed.append(postagem)

        for evento in self.eventos:
            feed.append(evento)

        if not feed:

            print(
                "Nenhuma publicação encontrada."
            )

            return

        for item in feed:

            print(item.publicar())

            print("-" * 40)

    # =====================================
    # ESTATÍSTICAS
    # =====================================

    def estatisticas(self):

        print("\n===== ESTATÍSTICAS =====")

        print(
            f"Alunos: {len(self.alunos)}"
        )

        print(
            f"Disciplinas: {len(self.disciplinas)}"
        )

        print(
            f"Rotinas: {len(self.rotinas)}"
        )

        print(
            f"Postagens: {len(self.postagens)}"
        )

        print(
            f"Eventos: {len(self.eventos)}"
        )
# =====================================================
# MENU PRINCIPAL
# =====================================================

sistema = SistemaFocusU()

while True:

    print("\n════════════════════════════")
    print("         FOCUS U")
    print("════════════════════════════")

    print("1 - Cadastrar Aluno")
    print("2 - Criar Disciplina")
    print("3 - Vincular Disciplina ao Aluno")
    print("4 - Criar Rotina")
    print("5 - Criar Postagem")
    print("6 - Criar Evento")

    print("7 - Listar Alunos")
    print("8 - Listar Disciplinas")
    print("9 - Listar Rotinas")

    print("10 - Exibir Feed")

    print("11 - Curtir Postagem")
    print("12 - Comentar Postagem")

    print("13 - Estatísticas")

    print("0 - Sair")

    opcao = input("\nEscolha uma opção: ")

    try:

        # =====================================
        # CADASTRAR ALUNO
        # =====================================

        if opcao == "1":

            nome = input("Nome: ")
            email = input("Email: ")
            matricula = input("Matrícula: ")

            aluno = Aluno(
                nome,
                email,
                matricula
            )

            sistema.adicionar_aluno(
                aluno
            )

            print(
                "\nAluno cadastrado com sucesso!"
            )

        # =====================================
        # CRIAR DISCIPLINA
        # =====================================

        elif opcao == "2":

            nome = input(
                "Nome da disciplina: "
            )

            professor = input(
                "Professor: "
            )

            disciplina = Disciplina(
                nome,
                professor
            )

            sistema.adicionar_disciplina(
                disciplina
            )

            print(
                "\nDisciplina criada!"
            )

        # =====================================
        # ASSOCIAR DISCIPLINA AO ALUNO
        # =====================================

        elif opcao == "3":

            if not sistema.alunos:

                print(
                    "Nenhum aluno cadastrado."
                )

                continue

            if not sistema.disciplinas:

                print(
                    "Nenhuma disciplina cadastrada."
                )

                continue

            print("\nALUNOS:")

            for i, aluno in enumerate(
                sistema.alunos
            ):

                print(
                    f"{i} - {aluno.nome}"
                )

            indice_aluno = int(
                input(
                    "\nEscolha o aluno: "
                )
            )

            print("\nDISCIPLINAS:")

            for i, disciplina in enumerate(
                sistema.disciplinas
            ):

                print(
                    f"{i} - {disciplina.nome}"
                )

            indice_disciplina = int(
                input(
                    "\nEscolha a disciplina: "
                )
            )

            sistema.alunos[
                indice_aluno
            ].adicionar_disciplina(
                sistema.disciplinas[
                    indice_disciplina
                ]
            )

            print(
                "\nDisciplina vinculada!"
            )

        # =====================================
        # CRIAR ROTINA
        # =====================================

        elif opcao == "4":

            atividade = input(
                "Atividade: "
            )

            tempo = int(
                input(
                    "Tempo de estudo (min): "
                )
            )

            rotina = Rotina(
                atividade,
                tempo
            )

            sistema.adicionar_rotina(
                rotina
            )

            print(
                "\nRotina criada!"
            )

        # =====================================
        # CRIAR POSTAGEM
        # =====================================

        elif opcao == "5":

            if not sistema.alunos:

                print(
                    "Cadastre um aluno primeiro."
                )

                continue

            print("\nALUNOS:")

            for i, aluno in enumerate(
                sistema.alunos
            ):

                print(
                    f"{i} - {aluno.nome}"
                )

            indice = int(
                input(
                    "\nAutor da postagem: "
                )
            )

            titulo = input(
                "Título: "
            )

            conteudo = input(
                "Conteúdo: "
            )

            postagem = Postagem(
                titulo,
                conteudo,
                sistema.alunos[indice]
            )

            sistema.adicionar_postagem(
                postagem
            )

            print(
                "\nPostagem criada!"
            )

        # =====================================
        # CRIAR EVENTO
        # =====================================

        elif opcao == "6":

            titulo = input(
                "Título do evento: "
            )

            data = input(
                "Data: "
            )

            horario = input(
                "Horário: "
            )

            evento = Evento(
                titulo,
                data,
                horario
            )

            sistema.adicionar_evento(
                evento
            )

            print(
                "\nEvento criado!"
            )

        # =====================================
        # LISTAR ALUNOS
        # =====================================

        elif opcao == "7":

            sistema.listar_alunos()

        # =====================================
        # LISTAR DISCIPLINAS
        # =====================================

        elif opcao == "8":

            sistema.listar_disciplinas()

        # =====================================
        # LISTAR ROTINAS
        # =====================================

        elif opcao == "9":

            sistema.listar_rotinas()

        # =====================================
        # EXIBIR FEED
        # =====================================

        elif opcao == "10":

            sistema.exibir_feed()

        # =====================================
        # CURTIR POSTAGEM
        # =====================================

        elif opcao == "11":

            if not sistema.postagens:

                print(
                    "Nenhuma postagem encontrada."
                )

                continue

            for i, postagem in enumerate(
                sistema.postagens
            ):

                print(
                    f"{i} - {postagem.titulo}"
                )

            indice = int(
                input(
                    "Escolha a postagem: "
                )
            )

            sistema.postagens[
                indice
            ].curtir()

            print(
                "\nCurtida registrada!"
            )

        # =====================================
        # COMENTAR POSTAGEM
        # =====================================

        elif opcao == "12":

            if not sistema.postagens:

                print(
                    "Nenhuma postagem encontrada."
                )

                continue

            for i, postagem in enumerate(
                sistema.postagens
            ):

                print(
                    f"{i} - {postagem.titulo}"
                )

            indice = int(
                input(
                    "Escolha a postagem: "
                )
            )

            comentario = input(
                "Comentário: "
            )

            sistema.postagens[
                indice
            ].comentar(
                comentario
            )

            print(
                "\nComentário adicionado!"
            )

        # =====================================
        # ESTATÍSTICAS
        # =====================================

        elif opcao == "13":

            sistema.estatisticas()

        # =====================================
        # SAIR
        # =====================================

        elif opcao == "0":

            print(
                "\nSaindo do Focus U..."
            )

            break

        else:

            print(
                "\nOpção inválida!"
            )

    except Exception as erro:

        print(
            f"\nErro: {erro}"
        )